In [2]:
import pandas as pd
import os 
import nltk
import csv
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk import sent_tokenize, word_tokenize, pos_tag
from nltk import NaiveBayesClassifier

In [3]:
df = pd.read_csv(r'C:\Users\ADMIN\OneDrive\Desktop\NLP\spam.csv')
df = pd.DataFrame(df, columns= ['v1','v2'])
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.columns = ['label', 'text']

In [5]:
df.head(10)

label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [6]:
df['spam'] = df['label'].map( {'spam': 1, 'ham': 0} ).astype(int)
df.head(15)

label                                               text  spam
0    ham  Go until jurong point, crazy.. Available only ...     0
1    ham                      Ok lar... Joking wif u oni...     0
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3    ham  U dun say so early hor... U c already then say...     0
4    ham  Nah I don't think he goes to usf, he lives aro...     0
5   spam  FreeMsg Hey there darling it's been 3 week's n...     1
6    ham  Even my brother is not like to speak with me. ...     0
7    ham  As per your request 'Melle Melle (Oru Minnamin...     0
8   spam  WINNER!! As a valued network customer you have...     1
9   spam  Had your mobile 11 months or more? U R entitle...     1
10   ham  I'm gonna be home soon and i don't want to tal...     0
11  spam  SIX chances to win CASH! From 100 to 20,000 po...     1
12  spam  URGENT! You have won a 1 week FREE membership ...     1
13   ham  I've been searching for the right words to tha...     0
14   ham                I HAVE A DATE ON SUNDAY WITH WILL!!     0

In [7]:
df['length'] = df['text'].apply(len)
df.head(10)

label                                               text  spam  length
0   ham  Go until jurong point, crazy.. Available only ...     0     111
1   ham                      Ok lar... Joking wif u oni...     0      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155
3   ham  U dun say so early hor... U c already then say...     0      49
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147
6   ham  Even my brother is not like to speak with me. ...     0      77
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160
8  spam  WINNER!! As a valued network customer you have...     1     157
9  spam  Had your mobile 11 months or more? U R entitle...     1     154

In [8]:
df.head(10)

label                                               text  spam  length
0   ham  Go until jurong point, crazy.. Available only ...     0     111
1   ham                      Ok lar... Joking wif u oni...     0      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155
3   ham  U dun say so early hor... U c already then say...     0      49
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147
6   ham  Even my brother is not like to speak with me. ...     0      77
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160
8  spam  WINNER!! As a valued network customer you have...     1     157
9  spam  Had your mobile 11 months or more? U R entitle...     1     154

In [12]:
del df['length']
del df['spam']

In [9]:
df.head(10)

label                                               text  spam  length
0   ham  Go until jurong point, crazy.. Available only ...     0     111
1   ham                      Ok lar... Joking wif u oni...     0      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155
3   ham  U dun say so early hor... U c already then say...     0      49
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147
6   ham  Even my brother is not like to speak with me. ...     0      77
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160
8  spam  WINNER!! As a valued network customer you have...     1     157
9  spam  Had your mobile 11 months or more? U R entitle...     1     154

In [10]:
#Removing Puntuations

In [11]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [12]:
def rm_punc(text):
    new_text = ''.join([char for char in text if char not in string.punctuation])
    return new_text

In [13]:
df['no_punc'] = df['text'].apply(lambda row : rm_punc(row))

In [14]:
df.head(10)

label                                               text  spam  length  \
0   ham  Go until jurong point, crazy.. Available only ...     0     111   
1   ham                      Ok lar... Joking wif u oni...     0      29   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155   
3   ham  U dun say so early hor... U c already then say...     0      49   
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61   
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147   
6   ham  Even my brother is not like to speak with me. ...     0      77   
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160   
8  spam  WINNER!! As a valued network customer you have...     1     157   
9  spam  Had your mobile 11 months or more? U R entitle...     1     154   

                                             no_punc  
0  Go until jurong point crazy Available only in ...  
1                            Ok lar Joking wif u oni  
2  Free entry in 2 a wkly comp to win FA Cup fina...  
3        U dun say so early hor U c already then say  
4  Nah I dont think he goes to usf he lives aroun...  
5  FreeMsg Hey there darling its been 3 weeks now...  
6  Even my brother is not like to speak with me T...  
7  As per your request Melle Melle Oru Minnaminun...  
8  WINNER As a valued network customer you have b...  
9  Had your mobile 11 months or more U R entitled...

In [15]:
#TOKENIZATION
import re

In [16]:
def tok(text):
    tokens = re.split('\W+',text)
    return tokens

In [17]:
df['tokenized_text'] = df['no_punc'].apply(lambda row: tok(row.lower()))
df.head(10)

label                                               text  spam  length  \
0   ham  Go until jurong point, crazy.. Available only ...     0     111   
1   ham                      Ok lar... Joking wif u oni...     0      29   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155   
3   ham  U dun say so early hor... U c already then say...     0      49   
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61   
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147   
6   ham  Even my brother is not like to speak with me. ...     0      77   
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160   
8  spam  WINNER!! As a valued network customer you have...     1     157   
9  spam  Had your mobile 11 months or more? U R entitle...     1     154   

                                             no_punc  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   
5  FreeMsg Hey there darling its been 3 weeks now...   
6  Even my brother is not like to speak with me T...   
7  As per your request Melle Melle Oru Minnaminun...   
8  WINNER As a valued network customer you have b...   
9  Had your mobile 11 months or more U R entitled...   

                                      tokenized_text  
0  [go, until, jurong, point, crazy, available, o...  
1                     [ok, lar, joking, wif, u, oni]  
2  [free, entry, in, 2, a, wkly, comp, to, win, f...  
3  [u, dun, say, so, early, hor, u, c, already, t...  
4  [nah, i, dont, think, he, goes, to, usf, he, l...  
5  [freemsg, hey, there, darling, its, been, 3, w...  
6  [even, my, brother, is, not, like, to, speak, ...  
7  [as, per, your, request, melle, melle, oru, mi...  
8  [winner, as, a, valued, network, customer, you...  
9  [had, your, mobile, 11, months, or, more, u, r...

In [18]:
#Removing StopWords

In [19]:
stopwords = nltk.corpus.stopwords.words('english')
stopwords[:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [20]:
def rm_sw(text):
    clean_text = [word for word in text if word not in stopwords]
    return clean_text

In [21]:
df['clean_text'] = df['tokenized_text'].apply(lambda row : rm_sw(row))
df.head(10)

label                                               text  spam  length  \
0   ham  Go until jurong point, crazy.. Available only ...     0     111   
1   ham                      Ok lar... Joking wif u oni...     0      29   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155   
3   ham  U dun say so early hor... U c already then say...     0      49   
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61   
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147   
6   ham  Even my brother is not like to speak with me. ...     0      77   
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160   
8  spam  WINNER!! As a valued network customer you have...     1     157   
9  spam  Had your mobile 11 months or more? U R entitle...     1     154   

                                             no_punc  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   
5  FreeMsg Hey there darling its been 3 weeks now...   
6  Even my brother is not like to speak with me T...   
7  As per your request Melle Melle Oru Minnaminun...   
8  WINNER As a valued network customer you have b...   
9  Had your mobile 11 months or more U R entitled...   

                                      tokenized_text  \
0  [go, until, jurong, point, crazy, available, o...   
1                     [ok, lar, joking, wif, u, oni]   
2  [free, entry, in, 2, a, wkly, comp, to, win, f...   
3  [u, dun, say, so, early, hor, u, c, already, t...   
4  [nah, i, dont, think, he, goes, to, usf, he, l...   
5  [freemsg, hey, there, darling, its, been, 3, w...   
6  [even, my, brother, is, not, like, to, speak, ...   
7  [as, per, your, request, melle, melle, oru, mi...   
8  [winner, as, a, valued, network, customer, you...   
9  [had, your, mobile, 11, months, or, more, u, r...   

                                          clean_text  
0  [go, jurong, point, crazy, available, bugis, n...  
1                     [ok, lar, joking, wif, u, oni]  
2  [free, entry, 2, wkly, comp, win, fa, cup, fin...  
3      [u, dun, say, early, hor, u, c, already, say]  
4  [nah, dont, think, goes, usf, lives, around, t...  
5  [freemsg, hey, darling, 3, weeks, word, back, ...  
6  [even, brother, like, speak, treat, like, aids...  
7  [per, request, melle, melle, oru, minnaminungi...  
8  [winner, valued, network, customer, selected, ...  
9  [mobile, 11, months, u, r, entitled, update, l...

In [22]:
ps = nltk.PorterStemmer()

In [23]:
def stemming(tokenized_text):
    stemmed_text = [ps.stem(word) for word in tokenized_text]
    return stemmed_text

In [24]:
df['stemmed_text'] = df.clean_text.apply(lambda row : stemming(row))
df[['text','tokenized_text','stemmed_text']].head()

text  \
0  Go until jurong point, crazy.. Available only ...   
1                      Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3  U dun say so early hor... U c already then say...   
4  Nah I don't think he goes to usf, he lives aro...   

                                      tokenized_text  \
0  [go, until, jurong, point, crazy, available, o...   
1                     [ok, lar, joking, wif, u, oni]   
2  [free, entry, in, 2, a, wkly, comp, to, win, f...   
3  [u, dun, say, so, early, hor, u, c, already, t...   
4  [nah, i, dont, think, he, goes, to, usf, he, l...   

                                        stemmed_text  
0  [go, jurong, point, crazi, avail, bugi, n, gre...  
1                       [ok, lar, joke, wif, u, oni]  
2  [free, entri, 2, wkli, comp, win, fa, cup, fin...  
3      [u, dun, say, earli, hor, u, c, alreadi, say]  
4  [nah, dont, think, goe, usf, live, around, tho...

In [25]:
def final_text(stemmed_text):
    get_final_text = " ".join([word for word in stemmed_text])
    return get_final_text

In [26]:
df['final_text'] = df.stemmed_text.apply(lambda row : final_text(row))
df.head(10)

label                                               text  spam  length  \
0   ham  Go until jurong point, crazy.. Available only ...     0     111   
1   ham                      Ok lar... Joking wif u oni...     0      29   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1     155   
3   ham  U dun say so early hor... U c already then say...     0      49   
4   ham  Nah I don't think he goes to usf, he lives aro...     0      61   
5  spam  FreeMsg Hey there darling it's been 3 week's n...     1     147   
6   ham  Even my brother is not like to speak with me. ...     0      77   
7   ham  As per your request 'Melle Melle (Oru Minnamin...     0     160   
8  spam  WINNER!! As a valued network customer you have...     1     157   
9  spam  Had your mobile 11 months or more? U R entitle...     1     154   

                                             no_punc  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   
5  FreeMsg Hey there darling its been 3 weeks now...   
6  Even my brother is not like to speak with me T...   
7  As per your request Melle Melle Oru Minnaminun...   
8  WINNER As a valued network customer you have b...   
9  Had your mobile 11 months or more U R entitled...   

                                      tokenized_text  \
0  [go, until, jurong, point, crazy, available, o...   
1                     [ok, lar, joking, wif, u, oni]   
2  [free, entry, in, 2, a, wkly, comp, to, win, f...   
3  [u, dun, say, so, early, hor, u, c, already, t...   
4  [nah, i, dont, think, he, goes, to, usf, he, l...   
5  [freemsg, hey, there, darling, its, been, 3, w...   
6  [even, my, brother, is, not, like, to, speak, ...   
7  [as, per, your, request, melle, melle, oru, mi...   
8  [winner, as, a, valued, network, customer, you...   
9  [had, your, mobile, 11, months, or, more, u, r...   

                                          clean_text  \
0  [go, jurong, point, crazy, available, bugis, n...   
1                     [ok, lar, joking, wif, u, oni]   
2  [free, entry, 2, wkly, comp, win, fa, cup, fin...   
3      [u, dun, say, early, hor, u, c, already, say]   
4  [nah, dont, think, goes, usf, lives, around, t...   
5  [freemsg, hey, darling, 3, weeks, word, back, ...   
6  [even, brother, like, speak, treat, like, aids...   
7  [per, request, melle, melle, oru, minnaminungi...   
8  [winner, valued, network, customer, selected, ...   
9  [mobile, 11, months, u, r, entitled, update, l...   

                                        stemmed_text  \
0  [go, jurong, point, crazi, avail, bugi, n, gre...   
1                       [ok, lar, joke, wif, u, oni]   
2  [free, entri, 2, wkli, comp, win, fa, cup, fin...   
3      [u, dun, say, earli, hor, u, c, alreadi, say]   
4  [nah, dont, think, goe, usf, live, around, tho...   
5  [freemsg, hey, darl, 3, week, word, back, id, ...   
6  [even, brother, like, speak, treat, like, aid,...   
7  [per, request, mell, mell, oru, minnaminungint...   
8  [winner, valu, network, custom, select, receiv...   
9  [mobil, 11, month, u, r, entitl, updat, latest...   

                                          final_text  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4          nah dont think goe usf live around though  
5  freemsg hey darl 3 week word back id like fun ...  
6      even brother like speak treat like aid patent  
7  per request mell mell oru minnaminungint nurun...  
8  winner valu network custom select receivea 900...  
9  mobil 11 month u r entitl updat latest colour ...

In [27]:
df[['text', 'final_text']].head(10)

text  \
0  Go until jurong point, crazy.. Available only ...   
1                      Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3  U dun say so early hor... U c already then say...   
4  Nah I don't think he goes to usf, he lives aro...   
5  FreeMsg Hey there darling it's been 3 week's n...   
6  Even my brother is not like to speak with me. ...   
7  As per your request 'Melle Melle (Oru Minnamin...   
8  WINNER!! As a valued network customer you have...   
9  Had your mobile 11 months or more? U R entitle...   

                                          final_text  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4          nah dont think goe usf live around though  
5  freemsg hey darl 3 week word back id like fun ...  
6      even brother like speak treat like aid patent  
7  per request mell mell oru minnaminungint nurun...  
8  winner valu network custom select receivea 900...  
9  mobil 11 month u r entitl updat latest colour ...

In [28]:
sms = df['final_text']

In [29]:
print(sms)

0       go jurong point crazi avail bugi n great world...
1                                   ok lar joke wif u oni
2       free entri 2 wkli comp win fa cup final tkt 21...
3                     u dun say earli hor u c alreadi say
4               nah dont think goe usf live around though
                              ...                        
5567    2nd time tri 2 contact u u 750 pound prize 2 c...
5568                                b go esplanad fr home
5569                              piti mood soani suggest
5570    guy bitch act like id interest buy someth els ...
5571                                       rofl true name
Name: final_text, Length: 5572, dtype: object


In [30]:
#training_set = sms[:2800]

In [31]:
#testing_set = sms[2800:]

In [32]:
#classifier = nltk.NaiveBayesClassifier.train(training_set)
#print("Naive Bayes Algo Accuracy : ",(nltk.classify.accuracy(classifier, testing_Set))*100)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tfidf_model=TfidfVectorizer()
tfidf_vec=tfidf_model.fit_transform(sms)
tfidf_data=pd.DataFrame(tfidf_vec.toarray())


In [93]:
final_data =  tfidf_data
final_data.head()


0     1     2     3     4     5     6     7     8     9     ...  7966  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

   7967  7968  7969  7970  7971  7972  7973  7974  7975  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 7976 columns]

In [39]:
#CountVectorizer Function
from sklearn.feature_extraction.text import CountVectorizer
sms = df['final_text']
vectorizer = CountVectorizer()
vectorizer.fit(sms)
print(vectorizer.vocabulary_)

{'go': 3268, 'jurong': 4034, 'point': 5504, 'crazi': 2208, 'avail': 1320, 'bugi': 1719, 'great': 3359, 'world': 7735, 'la': 4175, 'buffet': 1717, 'cine': 1991, 'got': 3321, 'amor': 1132, 'wat': 7535, 'ok': 5135, 'lar': 4210, 'joke': 4000, 'wif': 7648, 'oni': 5165, 'free': 3088, 'entri': 2748, 'wkli': 7694, 'comp': 2087, 'win': 7661, 'fa': 2866, 'cup': 2254, 'final': 2967, 'tkt': 7061, '21st': 451, 'may': 4567, '2005': 438, 'text': 6924, '87121': 858, 'receiv': 5823, 'questionstd': 5737, 'txt': 7238, 'ratetc': 5783, 'appli': 1204, '08452810075over18': 71, 'dun': 2625, 'say': 6089, 'earli': 2641, 'hor': 3639, 'alreadi': 1105, 'nah': 4853, 'dont': 2549, 'think': 6990, 'goe': 3280, 'usf': 7365, 'live': 4329, 'around': 1242, 'though': 7006, 'freemsg': 3096, 'hey': 3549, 'darl': 2309, 'week': 7572, 'word': 7724, 'back': 1363, 'id': 3742, 'like': 4298, 'fun': 3148, 'still': 6631, 'tb': 6865, 'xxx': 7853, 'std': 6608, 'chg': 1940, 'send': 6161, '150': 350, 'rcv': 5794, 'even': 2795, 'brother':

In [40]:
vec = vectorizer.transform(sms)
print(vec.shape)
print(vec.toarray())

(5572, 7976)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
vec

<5572x7976 sparse matrix of type '<class 'numpy.int64'>'
	with 46847 stored elements in Compressed Sparse Row format>

In [42]:
vec.shape[0]

5572

In [43]:
vec.shape[1]

7976

In [44]:
vec.nnz

46847

In [45]:
print( vec.nnz / (vec.shape[0] * vec.shape[1]) *100 )

0.10541090248491346


In [46]:
#TF-IDF 

In [47]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer().fit(vec)

In [48]:
data_tfidf = tfidf_transformer.transform(vec)

In [49]:
data_tfidf

<5572x7976 sparse matrix of type '<class 'numpy.float64'>'
	with 46847 stored elements in Compressed Sparse Row format>

In [50]:
import numpy as np
np.shape(data_tfidf)

(5572, 7976)

In [118]:
print(np.mean(data_tfidf))

0.00033208473357894874


In [52]:
#Splitting Training and Testing Sets

In [109]:
from sklearn.model_selection import train_test_split
data_tfidf_train, data_tfidf_test, label_train, label_test = train_test_split(data_tfidf, df['spam'], test_size=0.3, random_state=1 )

In [110]:
data_tfidf_train

<3900x7976 sparse matrix of type '<class 'numpy.float64'>'
	with 32817 stored elements in Compressed Sparse Row format>

In [111]:
data_tfidf_test

<1672x7976 sparse matrix of type '<class 'numpy.float64'>'
	with 14030 stored elements in Compressed Sparse Row format>

In [112]:
print(np.mean(data_tfidf_train))
print(np.mean(data_tfidf_test))
print(np.mean(label_train))
print(np.mean(label_test))

0.00033248164635509697
0.00033115892028530154
0.13564102564102565
0.1303827751196172


In [113]:
nb = MultinomialNB()

In [114]:
nb.fit(data_tfidf_train, label_train)

MultinomialNB()

In [115]:
y_pred_class = nb.predict(data_tfidf_test)

In [119]:
from sklearn import metrics
metrics.accuracy_score(label_test, y_pred_class)

0.9617224880382775

In [102]:
cf_matrix=metrics.confusion_matrix(label_test, y_pred_class)
cf_matrix

array([[1454,    0],
       [  64,  154]], dtype=int64)

In [103]:
#from scipy.sparse import  hstack
#X2 = hstack((data_tfidf ,np.array(df['length'])[:,None])).A

In [106]:
X2_train, X2_test, y2_train, y2_test = train_test_split(data_tfidf, df["label"], test_size=0.3, random_state=5)

In [107]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [108]:
spam_detect_model = MultinomialNB().fit(data_tfidf_train, label_train)
pred_test_MNB = spam_detect_model.predict(data_tfidf_test)
acc_MNB = accuracy_score(label_test, pred_test_MNB)
print(acc_MNB*100)

96.17224880382776
